package fr.chrono.model.interfaces;

public enum ConfigurationType {
	
	CONFIGURATION_1,//ARRIVAL
	CONFIGURATION_2,//START+ARRIVAL
	CONFIGURATION_3,//START+ARRIVAL+SERVER
	CONFIGURATION_4;//START+ARRIVAL*+SERVER
}
